"""Confirmed occurrences and local evidence, independent from UI and delivery.

IoU continuity is a lightweight spatial heuristic, not identity recognition.
Evidence requires the same per-person condition in consecutive observations.
"""

from dataclasses import dataclass, asdict
from datetime import datetime, timezone
import json
import math
import os
from pathlib import Path
import threading
import time
import unicodedata
from uuid import UUID, uuid4

import cv2
import numpy as np

from .preprocessing import preprocess_frame
from .rules import assess_people, person_detections, supports_ppe
from .types import Detection, FrameResult


@dataclass(frozen=True)
class CameraContext:
    camera_id: str = "camera-01"
    name: str = "Câmera 01"
    location: str = "Local não informado"

    def __post_init__(self):
        for field in ("camera_id", "name", "location"):
            value = getattr(self, field)
            if not isinstance(value, str) or not value.strip() or len(value) > 240:
                raise ValueError(f"{field} deve conter entre 1 e 240 caracteres.")


@dataclass(frozen=True)
class EventPolicy:
    trigger: str = "ppe"
    confirmation_seconds: float = 2.0
    cooldown_seconds: float = 60.0
    max_events: int = 500

    def __post_init__(self):
        if self.trigger not in {"ppe", "person"}:
            raise ValueError("Gatilho deve ser 'ppe' ou 'person'.")
        for field in ("confirmation_seconds", "cooldown_seconds"):
            value = getattr(self, field)
            if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or value < 0:
                raise ValueError(f"{field} deve ser um número finito maior ou igual a zero.")
        _validate_retention(self.max_events)


def _validate_retention(value: int) -> None:
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        raise ValueError("max_events deve ser um inteiro positivo.")


_LOCKS: dict[str, threading.RLock] = {}
_LOCKS_GUARD = threading.Lock()


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="microseconds")


def _atomic_json(path: Path, document: dict) -> None:
    temporary = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
    try:
        with temporary.open("x", encoding="utf-8") as handle:
            json.dump(document, handle, ensure_ascii=False, indent=2, allow_nan=False)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _ascii(value: str) -> str:
    return unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode().replace("\n", " ").replace("\r", " ")


def _stamp(frame: np.ndarray, event: dict) -> np.ndarray:
    """Append a legible banner without covering or modifying detections."""
    prepared = preprocess_frame(frame)
    width = max(640, prepared.shape[1])
    scale, row_height = 0.5, 25
    texts = [
        f"{event['camera_name']} | {event['location']}",
        f"UTC: {event['timestamp_utc']} | {event['model_mode']}",
        *event["reasons"],
    ]
    lines: list[str] = []
    for text in texts:
        remaining = _ascii(text)
        while remaining:
            end = len(remaining)
            while end > 1 and cv2.getTextSize(remaining[:end], cv2.FONT_HERSHEY_SIMPLEX, scale, 1)[0][0] > width - 24:
                end -= 1
            lines.append(remaining[:end])
            remaining = remaining[end:]
    height = prepared.shape[0]
    canvas = np.full((height + row_height * len(lines) + 16, width, 3), (26, 30, 38), dtype=np.uint8)
    canvas[:height, :prepared.shape[1]] = prepared
    for index, line in enumerate(lines):
        cv2.putText(canvas, line, (12, height + 24 + index * row_height), cv2.FONT_HERSHEY_SIMPLEX, scale, (235, 240, 245), 1, cv2.LINE_AA)
    return canvas


class EventStore:
    """Atomic event folders; operations synchronize across instances in process.

    Retention removes only complete folders generated by this schema containing
    exactly event.json and snapshot.jpg. Unrecognized files are never removed.
    Pending deliveries are retained beyond the limit, including after a crash.
    Multiple OS processes should use separate storage roots.
    """

    def __init__(self, root: Path | str = "reports/occurrences", max_events: int = 500):
        _validate_retention(max_events)
        self.root = Path(root).expanduser().resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self.max_events = max_events
        self.retention_warning = ""
        with _LOCKS_GUARD:
            self._lock = _LOCKS.setdefault(os.path.normcase(str(self.root)), threading.RLock())

    def _folder(self, event_id: str) -> Path:
        try:
            valid = str(UUID(event_id)) == event_id
        except (ValueError, TypeError, AttributeError):
            valid = False
        if not valid:
            raise ValueError("Identificador de ocorrência inválido.")
        folder = self.root / event_id
        if folder.is_symlink() or folder.resolve().parent != self.root:
            raise ValueError("Diretório de ocorrência inválido.")
        return folder

    def _read(self, folder: Path) -> dict | None:
        try:
            folder = self._folder(folder.name)
            metadata, snapshot = folder / "event.json", folder / "snapshot.jpg"
            if metadata.is_symlink() or snapshot.is_symlink() or not snapshot.is_file():
                return None
            event = json.loads(metadata.read_text(encoding="utf-8"))
            if not isinstance(event, dict) or type(event.get("schema_version")) is not int or event.get("schema_version") != 1 or event.get("producer") != "safeguard" or event.get("id") != folder.name:
                return None
            timestamp = datetime.fromisoformat(event["timestamp_utc"])
            if timestamp.tzinfo is None:
                return None
            CameraContext(event["camera_id"], event["camera_name"], event["location"])
            if event.get("kind") not in ("ppe", "person", "manual") or event.get("model_mode") not in ("demo", "ppe"):
                return None
            reasons = event.get("reasons")
            if not isinstance(reasons, list) or not reasons or any(not isinstance(reason, str) or not reason.strip() for reason in reasons):
                return None
            counts = event.get("counts")
            if not isinstance(counts, dict) or any(not isinstance(label, str) or type(count) is not int or count < 0 for label, count in counts.items()):
                return None
            if type(event.get("frame_index")) is not int or event["frame_index"] < 0:
                return None
            detections = event.get("detections")
            if not isinstance(detections, list):
                return None
            for detection in detections:
                if not isinstance(detection, dict) or type(detection.get("class_id")) is not int or detection["class_id"] < 0 or not isinstance(detection.get("label"), str):
                    return None
                confidence, bbox = detection.get("confidence"), detection.get("bbox")
                if type(confidence) not in (int, float) or not math.isfinite(confidence) or not 0 <= confidence <= 1:
                    return None
                if not isinstance(bbox, list) or len(bbox) != 4 or any(type(value) not in (int, float) or not math.isfinite(value) for value in bbox):
                    return None
            deliveries = event.get("deliveries")
            if not isinstance(deliveries, dict):
                return None
            for channel, delivery in deliveries.items():
                if not isinstance(channel, str) or not channel.strip() or len(channel) > 64 or not isinstance(delivery, dict):
                    return None
                status, detail = delivery.get("status"), delivery.get("detail")
                if not isinstance(status, str) or not status.strip() or len(status) > 64 or not isinstance(detail, str):
                    return None
                if datetime.fromisoformat(delivery["updated_at_utc"]).tzinfo is None:
                    return None
            # Paths on disk are reconstructed, never trusted from JSON.
            event["snapshot_path"] = str(snapshot)
            event["metadata_path"] = str(metadata)
            return event
        except (OSError, ValueError, KeyError, TypeError, OverflowError):
            return None

    def _list(self) -> list[dict]:
        events = [event for folder in self.root.iterdir() if folder.is_dir() and (event := self._read(folder)) is not None]
        return sorted(events, key=lambda item: (item["timestamp_utc"], item["id"]), reverse=True)

    def list_events(self, limit: int = 50) -> list[dict]:
        if isinstance(limit, bool) or not isinstance(limit, int) or limit < 0:
            raise ValueError("limit deve ser um inteiro maior ou igual a zero.")
        with self._lock:
            return self._list()[:limit]

    def _delete(self, event_id: str) -> bool:
        folder = self._folder(event_id)
        if self._read(folder) is None:
            return False
        children = list(folder.iterdir())
        if {child.name for child in children} != {"event.json", "snapshot.jpg"} or any(child.is_symlink() for child in children):
            return False
        for child in children:
            child.unlink()
        folder.rmdir()
        return True

    def delete(self, event_id: str) -> bool:
        """Delete a known occurrence, preserving foreign/incomplete directories."""
        with self._lock:
            return self._delete(event_id)

    def prune(self) -> int:
        with self._lock:
            return sum(self._delete(event["id"]) for event in self._list()[self.max_events:]
                       if not any(delivery["status"] == "pending" for delivery in event["deliveries"].values()))

    def _prune_after_write(self) -> None:
        """Housekeeping must never invalidate a successfully committed write."""
        try:
            self.prune()
            self.retention_warning = ""
        except Exception:
            self.retention_warning = (
                "Ocorrência salva, mas a limpeza de registros antigos falhou. "
                "O limite de armazenamento pode ser excedido; verifique permissões e espaço em disco."
            )

    def save(self, result: FrameResult, annotated_frame: np.ndarray, context: CameraContext,
             kind: str, reasons: list[str], demo_mode: bool) -> dict:
        if kind not in {"ppe", "person", "manual"}:
            raise ValueError("Tipo de ocorrência inválido.")
        if not reasons or any(not isinstance(reason, str) or not reason.strip() for reason in reasons):
            raise ValueError("A ocorrência precisa de pelo menos um motivo.")
        event_id = str(uuid4())
        folder = self._folder(event_id)
        event = {
            "schema_version": 1, "producer": "safeguard", "id": event_id, "timestamp_utc": _utc_now(),
            "camera_id": context.camera_id, "camera_name": context.name, "location": context.location,
            "kind": kind, "reasons": list(reasons), "model_mode": "demo" if demo_mode else "ppe",
            "counts": {str(label): int(count) for label, count in result.counts.items()},
            "detections": [
                {"class_id": int(d.class_id), "label": d.label, "confidence": float(d.confidence), "bbox": [float(value) for value in d.bbox]}
                for d in result.detections
            ],
            "frame_index": int(result.frame_index),
            "assessments": [asdict(item) for item in result.assessments],
            "ppe_executed": result.ppe_executed,
            "snapshot_path": str(folder / "snapshot.jpg"), "metadata_path": str(folder / "event.json"),
            "deliveries": {},
        }
        success, jpeg = cv2.imencode(".jpg", _stamp(annotated_frame, event), [cv2.IMWRITE_JPEG_QUALITY, 90])
        if not success:
            raise OSError("Não foi possível codificar a imagem da ocorrência.")
        with self._lock:
            pending = self.root / f".pending-{event_id}"
            pending.mkdir()
            try:
                (pending / "snapshot.jpg").write_bytes(jpeg.tobytes())
                _atomic_json(pending / "event.json", event)
                os.replace(pending, folder)
            except Exception:
                # Only these files belong to this operation. Never recurse.
                for name in ("snapshot.jpg", "event.json"):
                    (pending / name).unlink(missing_ok=True)
                if pending.exists() and not any(pending.iterdir()):
                    pending.rmdir()
                raise
            self._prune_after_write()
        return event

    def set_delivery(self, event_id: str, channel: str, status: str, detail: str = "") -> None:
        if not isinstance(channel, str) or not channel.strip() or len(channel) > 64:
            raise ValueError("Canal de entrega inválido.")
        if not isinstance(status, str) or not status.strip() or len(status) > 64:
            raise ValueError("Status de entrega inválido.")
        with self._lock:
            folder = self._folder(event_id)
            event = self._read(folder)
            if event is None:
                raise FileNotFoundError("Ocorrência não encontrada; pode ter sido removida pela retenção.")
            event.setdefault("deliveries", {})[channel] = {"status": status, "detail": str(detail)[:1000], "updated_at_utc": _utc_now()}
            _atomic_json(folder / "event.json", event)
            self._prune_after_write()


@dataclass
class _Track:
    person: Detection
    missing: tuple[str, ...]
    since: float


def _iou(first: Detection, second: Detection) -> float:
    ax1, ay1, ax2, ay2 = first.bbox
    bx1, by1, bx2, by2 = second.bbox
    intersection = max(0, min(ax2, bx2) - max(ax1, bx1)) * max(0, min(ay2, by2) - max(ay1, by1))
    union = max(0, ax2 - ax1) * max(0, ay2 - ay1) + max(0, bx2 - bx1) * max(0, by2 - by1) - intersection
    return intersection / union if union > 0 else 0.0


class EventService:
    """Confirm conditions for each spatial track, then throttle per camera.

    A missing observation, a changed missing-PPE set, or a >2-second gap resets
    confirmation. Ambiguous overlaps reset rather than mixing evidence between
    people. This intentionally conservative tracker cannot recognize identities.
    Call only for actual model inference, never the UI's synthetic preview.
    ``now`` may be media time for files or monotonic time for live sources.
    Evidence timestamps are wall-clock timestamps of analysis in UTC.
    """

    MAX_OBSERVATION_GAP_SECONDS = 2.0
    TRACK_IOU_THRESHOLD = 0.3

    def __init__(self, store: EventStore, context: CameraContext, policy: EventPolicy,
                 demo_mode: bool = True, model_names: dict[int, str] | None = None):
        self.store, self.context, self.policy = store, context, policy
        self.demo_mode, self.model_names = demo_mode, model_names
        self.store.max_events = policy.max_events
        self._tracks: list[_Track] = []
        self._last_observed: float | None = None
        self._last_event: float | None = None

    def reset_confirmation(self) -> None:
        """Discard incomplete continuity while preserving the event cooldown.

        Call when video timestamps become unavailable or continuity is lost.
        The next known timestamp starts a fresh observation interval.
        """
        self._tracks = []
        self._last_observed = None

    def process(self, result: FrameResult, annotated_frame: np.ndarray, now: float | None = None) -> dict | None:
        now = time.monotonic() if now is None else now
        if isinstance(now, bool) or not isinstance(now, (float, int)) or not math.isfinite(now):
            raise ValueError("O relógio da ocorrência deve ser um número finito.")
        if self._last_observed is not None:
            if now < self._last_observed:
                raise ValueError("O relógio de confirmação deve ser monotônico.")
            if now - self._last_observed > self.MAX_OBSERVATION_GAP_SECONDS:
                self._tracks = []
        self._last_observed = now
        if self.policy.trigger == "ppe":
            if self.demo_mode:
                self._tracks = []
                return None
            if result.ppe_executed:
                observations = [(item.person, item.absent if item.status == "unsafe" else ()) for item in result.assessments]
            else:
                # Single-stage legacy absence heuristics cannot confirm a PPE
                # event. Only explicit decisions from the cascade can do so.
                observations = []
        else:
            observations = [(person, ("person",)) for person in person_detections(result.detections)]

        # Require a unique match in both directions. At crossings, reset rather
        # than allowing one person's history to confirm another person's event.
        edges = {(old, new) for old, track in enumerate(self._tracks) for new, (person, _) in enumerate(observations)
                 if _iou(track.person, person) >= self.TRACK_IOU_THRESHOLD}
        matches = {new: old for old, new in edges
                   if sum(a == old for a, _ in edges) == 1 and sum(b == new for _, b in edges) == 1}
        updated = []
        reasons = []
        for index, (person, missing) in enumerate(observations):
            previous = self._tracks[matches[index]] if index in matches else None
            since = previous.since if previous and previous.missing == missing else now
            updated.append(_Track(person, missing, since))
            if missing and now - since >= self.policy.confirmation_seconds:
                if self.policy.trigger == "person":
                    reasons.append(f"Pessoa {index + 1} detectada; detecção observada durante {self.policy.confirmation_seconds:g}s de análise.")
                else:
                    labels = ["capacete" if kind == "helmet" else "colete" for kind in missing]
                    reasons.append(f"Pessoa {index + 1}: classe explícita de ausência de {' e '.join(labels)} durante {self.policy.confirmation_seconds:g}s observados (revisão visual necessária).")
        self._tracks = updated
        if not reasons or (self._last_event is not None and now - self._last_event < self.policy.cooldown_seconds):
            return None
        event = self.store.save(result, annotated_frame, self.context, self.policy.trigger, reasons, self.demo_mode)
        self._last_event = now
        return event
